---
title: "Publications"
---
  
* Association of electronic cigarette use and suicidal behaviors: a systematic review and meta-analysis

Journal: BMC Psychiatry

Link: https://link.springer.com/article/10.1186/s12888-024-06012-7

* Predictors of acute kidney injury in dengue patients: a systematic review and meta-analysis

Journal: Virology Journal

Link: https://link.springer.com/article/10.1186/s12985-024-02488-7 

* Postoperative elevated bed header position versus supine in the management of chronic subdural hematoma: a systematic review and meta-analysis

Journal: Acta Neurologica Belgica

Link: https://link.springer.com/article/10.1007/s13760-024-02571-4 

* Efficacy and safety of aldafermin in non-alcoholic steatohepatitis: A systematic review and meta-analysis of randomized controlled trials

Journal: Clinics and Research in Hepatology and Gastroenterology

Link: https://www.sciencedirect.com/science/article/pii/S2210740124000780 

* Charles Kelman: The Father of Phacoemulsification

Journal: Cureus

Link: https://pmc.ncbi.nlm.nih.gov/articles/PMC11225641/#:~:text=Charles%20D.,(3%2D4%20mm).

* Penetrating Keratoplasty versus Deep Anterior Lamellar Keratoplasty for Keratoconus: A Systematic Review and Meta-Analysis of 27,018 Eyes

Journal: Seminars in Ophthalmology

Link: https://www.tandfonline.com/doi/abs/10.1080/08820538.2025.2457583 

* Glasdegib combined with chemotherapy in the treatment of patients with acute myeloid leukemia: a comprehensive meta-analysis

Journal: Investigational New Drugs

Link: https://link.springer.com/article/10.1007/s10637-025-01528-5 

* Efficacy and Safety of Ontamalimab in Treating Inflammatory Bowel Disease: a Systematic Review and Meta-Analysis of Randomized Controlled Trials

Journal: Current Pharmacology Reports

Link: https://link.springer.com/article/10.1007/s40495-024-00363-1 

* Evaluating the efficacy and safety of survodutide for obesity: a systematic review and meta-analysis of randomized controlled trials

Journal: Baylor University Medical Center Proceedings

Link: https://www.tandfonline.com/doi/abs/10.1080/08998280.2025.2480512 

* Prevalence of vascular complications in Ehlers-Danlos syndrome: a systematic review and meta-analysis

Journal: Orphanet Journal of Rare Diseases

Link: https://link.springer.com/article/10.1186/s13023-025-03854-6 

* Efficacy and safety of Brivaracetam as adjunctive therapy in pediatric epilepsy: A systematic review and meta-analysis

Journal: Neurological Sciences

Link: https://link.springer.com/article/10.1007/s10072-025-08185-9

* Efficacy and safety of transjugular intrahepatic portosystemic shunt versus endoscopic variceal ligation for variceal rebleeding: a systematic review and meta-analysis

Journal: Annals of Medicine and Surgery

Link: https://journals.lww.com/annals-of-medicine-and-surgery/fulltext/2025/05000/efficacy_and_safety_of_transjugular_intrahepatic.48.aspx 

* Transcaval access for transcatheter aortic valve replacement: a systematic review and meta-analysis

Journal: Annals of Medicine and Surgery

Link: https://journals.lww.com/annals-of-medicine-and-surgery/fulltext/2025/05000/transcaval_access_for_transcatheter_aortic_valve.46.aspx

* Proton pump inhibitors after endoscopic band ligation: a systematic review and meta-analysis

Journal: Endoscopy

Link: https://www.thieme-connect.com/products/ejournals/html/10.1055/s-0045-1805355 

* Efficacy and Safety of Penetrating Keratoplasty and Deep Anterior Lamellar Keratoplasty in Corneal Macular Dystrophy: A Systematic Review and Meta‐Analysis

Journal: Journal of Ophthalmology

Link: https://onlinelibrary.wiley.com/doi/full/10.1155/joph/8867750

* Allvar Gullstrand: The Only Ophthalmologist Who Won the Nobel Prize

Journal: Cureus

Link: https://pmc.ncbi.nlm.nih.gov/articles/PMC11253073/

* Robot-assisted Endoscopic Submucosal Dissection in Gastrointestinal Lesions: A Systematic Review and Meta-Analysis

Journal: Clinics and Research in Hepatology and Gastroenterology

Link: https://www.sciencedirect.com/science/article/abs/pii/S2210740125002293

* Anticoagulation Timing After Stroke in Atrial Fibrillation: Evidence from a Systematic Review and Meta-Analysis

Journal: Clinical and Applied Thrombosis/Hemostasis

Link: https://journals.sagepub.com/doi/full/10.1177/10760296251410869

* Colorectal Cancer Screening and Mortality Trends in the United States Over 25 Years: A Story of Success and Inequity

Journal: Digestive Diseases and Sciences

Link: https://link.springer.com/article/10.1007/s10620-025-09472-3 

* Intravenous ferric carboxymaltose for iron deficiency in heart failure patients: A meta-analysis with trial sequential analysis

Journal: European Journal of Pharmacology

Link: https://www.sciencedirect.com/science/article/abs/pii/S0014299925010684

* Prevalence and Associated Risk Factors of Erectile Dysfunction Among Patients With Inflammatory Bowel Disease: An Updated Meta-Analysis

Journal: American Journal of Gastroenterology (ACG)

Link: https://journals.lww.com/ajg/fulltext/2025/10002/s1537_prevalence_and_associated_risk_factors_of.1538.aspx 

* Colorectal Cancer Screening and Mortality Trends in the US (1999–2024): A Story of Success and Inequity

Journal: American Journal of Gastroenterology (ACG)

Link: https://journals.lww.com/ajg/fulltext/2025/10002/s530_colorectal_cancer_screening_and_mortality.531.aspx

* A comprehensive systematic review of randomized controlled trials on anesthetic agents in children’s upper gastrointestinal endoscopy: highlighting safety concerns and efficacy

Journal: Naunyn-Schmiedeberg's Archives of Pharmacology

Link: https://link.springer.com/article/10.1007/s00210-025-04557-2 

* Efficacy and safety of hand suturing technique application in the endoscopic treatment of gastrointestinal tract tumors: a systematic review and meta-analysis

Journal: European Surgery

Link: https://link.springer.com/article/10.1007/s10353-025-00887-w

* The efficacy and safety of nanoemulsion compared to conventional cyclosporine in dry eye disease: A systematic review and meta-analysis

Journal: AJO International

Link: https://www.sciencedirect.com/science/article/pii/S2950253525000462

* Risk of hepatocellular carcinoma after receiving direct antiviral agents for hepatitis C virus: multicentric retrospective study

Journal: Gastroenterology

* Efficacy and safety of gastric electrical stimulation with adjunct pyloroplasty and pyloromyotomy in refractory gastroparesis: A systematic review and meta-analysis

Journal: Gastroenterology

* Trends in screening rates and mortality correlations in colorectal cancer: An analysis of BRFSS and CDC WONDER databases

Journal: Gastroenterology

* Endoscopic submucosal dissection with rubber bands and clips compared to conventional technique: A systematic review and meta-analysis

Journal: Digestive Diseases and Sciences

Link: https://link.springer.com/article/10.1007/s10620-025-09074-z

* Safety and efficacy of lumen-opposing metal stent compared to double-pigtail plastic stent in walled-off pancreas

Journal: Gastrointestinal Endoscopy

* Efficacy and Safety of Tofacitinib in Pediatric Ulcerative Colitis Patients: A Systematic Review

Journal: ASIDE Gastroenterology

* Traction-assisted endoscopic submucosal dissection: A systematic review and meta-analysis

Journal: Endoscopy

Link: https://www.thieme-connect.com/products/ejournals/html/10.1055/s-0045-1805514

* Endoscopic hand suturing after endoscopic submucosal dissection procedures: A systematic review and meta-analysis

Journal: Endoscopy

Link: https://www.thieme-connect.com/products/ejournals/html/10.1055/s-0045-1806573

* Gastric electrical stimulation combined with pyloromyotomy or pyloroplasty in gastroparesis patients: A systematic review and meta-analysis

Journal: Endoscopy

Link: https://www.thieme-connect.com/products/ejournals/html/10.1055/s-0045-1805253 

* Over-the-scope clips after endoscopic removal of duodenal tumors: A systematic review and meta-analysis

Journal: Endoscopy

Link: https://www.thieme-connect.com/products/ejournals/html/10.1055/s-0045-1806076

* Transcaval access for transcatheter aortic valve replacement: A systematic review and meta-analysis

Journal: Cardiovascular Interventions

Link: https://www.jacc.org/doi/abs/10.1016/j.jcin.2025.01.409

